site/Models/Speciality.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace site.Models
{
	public class Speciality
	{
		public int SpecialityId { get; set; }
		public string Name { get; set; }
		public List<UserSpec> Users { get; set; }
		public List<ProjectSpec> Projects { get; set; }
		
		public Speciality()
		{
			Users = new List<UserSpec>();
			Projects = new List<ProjectSpec>();
		}
		
		public override string ToString()
		{
			return Name;
		}
	}
}

site/ViewModels/SpecialityViewModel.cs
using System.Collections.Generic;

namespace site.ViewModels
{
    public class SpecialityViewModel
    {
        public List<string> Names { get; set; }
   
    }
}

site/Controllers/SpecialityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using site.Models;
using site.ViewModels;

namespace site.Controllers
{
    public class SpecialityController : Controller
    {

        private readonly ApplicationContext _db;
        private readonly UserManager<User> _userManager;
        public SpecialityController(ApplicationContext db, UserManager<User> userManager)
        {
            _db = db;
            _userManager = userManager;
        }
        
        public IActionResult Add()
        {
            // TODO: РОЛИ РОЛИ РОЛИ
            string nikita = _userManager.GetUserId(HttpContext.User);
            ViewBag.nikita = nikita;
            if (nikita != "87759cdf-3b58-483b-a738-f79a051bac23" && nikita != "4d980ae0-2592-43fa-a2c1-35f8789102b7")
            {
                return NotFound();
            }
            ViewBag.sp = _db.Specialities.ToList();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(SpecialityViewModel model)
        {
            // TODO: РОЛИ РОЛИ РОЛИ
//            string nikita = _userManager.GetUserId(HttpContext.User);
//            ViewBag.nikita = nikita;
//            if (nikita != "87759cdf-3b58-483b-a738-f79a051bac23" && nikita != "4d980ae0-2592-43fa-a2c1-35f8789102b7")
//            {
//                return NotFound();
//            }
            if (ModelState.IsValid)
            {
                foreach (var name in model.Names)
                {
                    Speciality spec = new Speciality
                    {
                        Name = name
                    };
                    await _db.Specialities.AddAsync(spec);
                    await _db.SaveChangesAsync();
                }
            }

            return RedirectToAction("Index", "Home");

        }
    }
}

site/Views/Speciality/Add.cshtml
@model site.ViewModels.SpecialityViewModel;
@{
    Layout = "_Header_Footer";
    ViewBag.Title = "Добавление технологии";
}

<section class="add">
    <div class="container">
        <h2 class="h2-common">Добавление новой специальности/технологии</h2>
        <form asp-action="Add" asp-controller="Speciality" enctype="multipart/form-data" method="post" id = "addForm">
            <div asp-validation-summary="All" class="text-danger"></div>
            @* <input type="hidden" asp-for="SpecialityId" /> *@
            <div class="group">
                <label >Название специальности/технологии</label>
                <input type="text" asp-for="Names" required>      
            </div>

            <button id = "add" class="bttn-light">Добавить еще</button>
            <input type="submit" class="bttn-dark">
        </form>
    </div>
</section>