site/Models/Experience.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace site.Models
{
	public class Experience
	{
		public int ExperienceId { get; set; }
		public string Title { get; set; }
		public string Description { get; set; }
		public string Link { get; set; }
		public DateTime StartDate { get; set; }
		public DateTime FinishDate { get; set; }
		public bool IsWork { get; set; }
		public bool Now { get; set; }
		private string _year;
		public string Year
		{
			get
			{
				string tempMonthStart = StartDate.Month.ToString().Length == 1 ? $"0{StartDate.Month}" : StartDate.Month.ToString();
				string tempMonthFinish = FinishDate.Month.ToString().Length == 1 ? $"0{FinishDate.Month}" : FinishDate.Month.ToString();
				if (!Now)
					_year = $"{tempMonthStart}.{StartDate.Year}-{tempMonthFinish}.{FinishDate.Year}";
				else
					_year = $"{tempMonthStart}.{StartDate.Year}-наст. время";
				return _year;
			}
		}
	}
}

site/ViewModels/ExperienceViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace site.ViewModels
{
    public class ExperienceViewModel
    {
        public int Id { get; set; }
        
        [Display(Name = "Название")]
        public string Title { get; set; }
        [Display(Name = "Описание")]
        public string Description { get; set; }
        [Display(Name = "Ссылка, если есть")]
        public string Link { get; set; }
        
        [Display(Name = "Дата начала")]
        public DateTime StartDate { get; set; }
        public string StartDateString => StartDate.ToString("yyyy-MM-dd");
        
        [Display(Name = "Дата окончания")]
        public DateTime FinishDate { get; set; }

        public string FinishDateString => FinishDate.ToString("yyyy-MM-dd");
        
        [Display(Name = "Работа")]
        public bool IsWork { get; set; }
        
        [Display(Name = "По настоящее время")]
        public bool IsNow { get; set; }
        
    }
}

site/Controllers/ExperienceController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using site.Models;
using site.ViewModels;

namespace site.Controllers
{
    public class ExperienceController : Controller
    {
        private UserManager<User> _userManager;
        private ApplicationContext _db;

        public ExperienceController(UserManager<User> userManager, ApplicationContext db)
        {
            _userManager = userManager;
            _db = db;
        }
        
        public async Task<IActionResult> Edit(int id)
        {
            User user = await _db.Users.Include(e => e.Experiences).FirstOrDefaultAsync(u => u.Id == _userManager.GetUserId(User));
            Experience exp = user.Experiences.FirstOrDefault(l => l.ExperienceId == id);
            if (exp != null)
            {
                ExperienceViewModel viewModel = new ExperienceViewModel
                {
                    Id = exp.ExperienceId,
                    Title = exp.Title,
                    Link = exp.Link,
                    Description = exp.Description,
                    StartDate = exp.StartDate,
                    FinishDate = exp.FinishDate,
                    IsWork = exp.IsWork,
                    IsNow = exp.Now
                };
                return View(viewModel);
            }
            else
            {
                return NotFound();
            }
            
        }
        
        [HttpPost]
        public async Task<IActionResult> Edit(ExperienceViewModel model)
        {
            if (ModelState.IsValid)
            {    
                User user = await _db.Users.Include(e => e.Experiences).FirstOrDefaultAsync(u => u.Id == _userManager.GetUserId(User));
                Experience exp = user.Experiences.FirstOrDefault(l => l.ExperienceId == model.Id);
                if (exp != null)
                {
                    exp.Title = model.Title;
                    exp.Link = model.Link;
                    exp.Description = model.Description;
                    exp.IsWork = model.IsWork;
                    exp.Now = model.IsNow;
                    exp.StartDate = model.StartDate;
                    exp.FinishDate = model.FinishDate;
                }

                _db.Users.Update(user);
                await _db.SaveChangesAsync();

            }
                
            

            return RedirectToAction("Index", "Home");
            
        }

        public async Task<IActionResult> Delete(int id)
        {
            User user = await _db.Users.Include(e => e.Experiences).FirstOrDefaultAsync(u => u.Id == _userManager.GetUserId(User));
            Experience exp = user.Experiences.FirstOrDefault(l => l.ExperienceId == id);
            user.Experiences.Remove(exp);
            _db.Users.Update(user);
            await _db.SaveChangesAsync();
                
            return RedirectToAction("Profile", "Account");
        }
    }
}

site/Views/Experience/Edit.cshtml
@model site.ViewModels.ExperienceViewModel
@{
    Layout = "_Header_Footer";
    ViewBag.Title = "Редактивароние опыта";
}
<section class="add">
    <div class="container">
        <h2 class="h2-common">Редактирование опыта</h2>
        <form asp-action="Edit" asp-controller="Experience" enctype="multipart/form-data">
            <div class="edit__courses__group">
                <div class="edit__group">
                    @Html.LabelFor(m => m.Link, new { @class = "second_label"})
                    @Html.EditorFor(m => m.Link)
                </div>
                
                <div class="edit__group">
                    @Html.LabelFor(m => m.Title, new { @class = "second_label"})
                    @Html.EditorFor(m => m.Title)
                </div>
                
                @Html.LabelFor(m => m.Description, new { @class = "second_label"})
                @Html.TextAreaFor(m => m.Description, new { @class = "anime", @id="aboutyou" })
                @Html.LabelFor(m => m.StartDate, new { @class = "second_label"})
                <input type="date" value="@Model.StartDateString" name = "StartDate">
                    
                @Html.LabelFor(m => m.FinishDate, new { @class = "second_label"})
                <input type="date" value="@Model.FinishDateString" name = "FinishDate">
                    
  
                    
                    
                @Html.LabelFor(m => m.IsWork, new { @class = "second_label"})
                @Html.EditorFor(m => m.IsWork)
  
                @Html.LabelFor(m => m.IsNow, new { @class = "second_label"})
                @Html.EditorFor(m => m.IsNow)
            
            </div>
            <input type="submit" class="bttn-dark">
        </form>
        @{
            string toDelete = $"/Experience/Delete/{Model.Id}";
        }
        <a href="@toDelete" class = "bttn-delete" style = "margin-top: 15px">Удалить</a>

    </div>
</section>